default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  pool: 5

development:
  <<: *default
  database: sleep_tracker_development

test:
  <<: *default
  database: sleep_tracker_test

production:
  <<: *default
  database: sleep_tracker_production
  username: sleep_tracker
  password: <%= ENV["POSTGRES_PASSWORD"] %>
